<template>
  <div class="loadingio-spinner-rolling-5uk6ngeemhr">
    <div class="ldio-b0tkyrpz95s">
      <div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: "base-loading"
};
</script>

<style>
@keyframes ldio-b0tkyrpz95s {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-b0tkyrpz95s div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #2d3748;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-b0tkyrpz95s div {
  animation: ldio-b0tkyrpz95s 1s linear infinite;
  top: 100px;
  left: 100px;
}
.loadingio-spinner-rolling-5uk6ngeemhr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-b0tkyrpz95s {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-b0tkyrpz95s div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>